apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: 3000-tcp
      port: 3000
      targetPort: 3000
    - name: "443"
      port: 443
      targetPort: 443
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    matchLabels: {{ .Values.appName }}
    identifier: {{ .Values.appName }}
status:
  loadBalancer: {}
