apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.appName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-deployment
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}-deployment
    spec:
      containers:
        - env:
          - name: MONGODB_URL
            value: "mongodb://username:password@mongo-db-database:27017/"
          image: {{ .Values.deployment.imageReact }}:{{ .Values.deployment.tag }}
          name: {{ .Values.appName }}
          ports:
            - containerPort: 3000
           # - containerPort: 443
           # - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
