apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.dbName }}-database
  name: {{ .Values.dbName }}-database
spec:
  ports:
    - name: "27017"
      port: {{ .Values.mongoPort }}
      targetPort: {{ .Values.mongoPort }}
  selector:
    app: {{ .Values.dbName }}-database
status:
  loadBalancer: {}
