apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.dbName }}
    spec:
      containers:
        - image: mongo:latest
          name: db-container
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Values.dbName }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.dbName }}
          persistentVolumeClaim:
            claimName: {{ .Values.dbName }}
status: {}
