apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.dbName }}
  name: {{ .Values.dbName }}
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: {{ .Values.dbName }}
status:
  loadBalancer: {}
