apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.dbName }}-database
  name: {{ .Values.dbName }}-database
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 32000
  selector:
    app: {{ .Values.dbName }}-database
  type: NodePort
status:
  loadBalancer: {}
