apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.dbName }}-database
  name: {{ .Values.dbName }}-database
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: {{ .Values.dbName }}-database
  type: NodePort
status:
  loadBalancer: {}
