version: '3'

services:
  # mongoDB service
  mongo_db: 
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    
  # reactJS service
  api:
    build: .
    ports: 
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://mongo_db:27017/
    depends_on:
      - mongo_db
    expose:
      - 3000
      - 443
      - 80  
volumes:
  mongo_db: {}
